export const FIND_VEHICULES_BY_CATEGORY_REQUEST = 'FIND_VEHICULES_BY_CATEGORY_REQUEST';
export const FIND_VEHICULES_BY_CATEGORY_SUCCESS = 'FIND_VEHICULES_BY_CATEGORY_SUCCESS';
export const FIND_VEHICULES_BY_CATEGORY_FAILURE = 'FIND_VEHICULES_BY_CATEGORY_FAILURE';


export const FIND_VEHICULE_BY_ID_REQUEST = 'FIND_VEHICULE_BY_ID_REQUEST';
export const FIND_VEHICULE_BY_ID_SUCCESS = 'FIND_VEHICULE_BY_ID_SUCCESS';
export const FIND_VEHICULE_BY_ID_FAILURE = 'FIND_VEHICULE_BY_ID_FAILURE';


export const CREATE_VEHICULE_REQUEST = 'CREATE_VEHICULE_REQUEST';
export const CREATE_VEHICULE_SUCCESS = 'CREATE_VEHICULE_SUCCESS';
export const CREATE_VEHICULE_FAILURE = 'CREATE_VEHICULE_FAILURE';

export const UPDATE_VEHICULE_REQUEST = "UPDATE_VEHICULE_REQUEST";
export const UPDATE_VEHICULE_SUCCESS = "UPDATE_VEHICULE_SUCCESS";
export const UPDATE_VEHICULE_FAILURE = "UPDATE_VEHICULE_FAILURE";

export const DELETE_VEHICULE_REQUEST = "DELETE_VEHICULE_REQUEST";
export const DELETE_VEHICULE_SUCCESS = "DELETE_VEHICULE_SUCCESS";
export const DELETE_VEHICULE_FAILURE = "DELETE_VEHICULE_FAILURE";

export const FIND_ALL_VEHICULES_REQUEST = "FIND_ALL_VEHICULES_REQUEST";
export const FIND_ALL_VEHICULES_SUCCESS = "FIND_ALL_VEHICULES_SUCCESS";
export const FIND_ALL_VEHICULES_FAILURE = "FIND_ALL_VEHICULES_FAILURE";

export const ORDER_VEHICULE_REQUEST = "ORDER_VEHICULE_REQUEST";
export const ORDER_VEHICULE_SUCCESS = "ORDER_VEHICULE_SUCCESS";
export const ORDER_VEHICULE_FAILURE = "ORDER_VEHICULE_FAILURE";
