
export const CREATE_VEHICULE_REQUEST = 'CREATE_VEHICULE_REQUEST';
export const CREATE_VEHICULE_SUCCESS = 'CREATE_VEHICULE_SUCCESS';
export const CREATE_VEHICULE_FAILURE = 'CREATE_VEHICULE_FAILURE';

export const GET_VEHICULES_REQUEST = 'GET_VEHICULE_REQUEST';
export const GET_VEHICULES_SUCCESS = 'GET_VEHICULE_SUCCESS';
export const GET_VEHICULES_FAILURE = 'GET_VEHICULE_FAILURE';

export const UPDATE_VEHICULE_REQUEST = "UPDATE_VEHICULE_REQUEST";
export const UPDATE_VEHICULE_SUCCESS = "UPDATE_VEHICULE_SUCCESS";
export const UPDATE_VEHICULE_FAILURE = "UPDATE_VEHICULE_FAILURE";

export const DELETE_VEHICULE_REQUEST = "DELETE_VEHICULE_REQUEST";
export const DELETE_VEHICULE_SUCCESS = "DELETE_VEHICULE_SUCCESS";
export const DELETE_VEHICULE_FAILURE = "DELETE_VEHICULE_FAILURE";